# Generated by Django 5.2.4 on 2025-09-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pinned', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='expires_on',
        ),
        migrations.AddField(
            model_name='notice',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateField(blank=True, db_column='expires_on', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(default='Admin', max_length=120),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Exam', 'Exam'), ('Maintenance', 'Maintenance'), ('Event', 'Event'), ('Emergency', 'Emergency')], default='General', max_length=32),
        ),
        migrations.AlterModelTable(
            name='notice',
            table='notices_notice',
        ),
    ]
